create TABLE catalogservice.book (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   title VARCHAR(255),
   original_title VARCHAR(255),
   isbn VARCHAR(255),
   release_date VARCHAR(255),
   edition_date VARCHAR(255),
   genre VARCHAR(255),
   edition VARCHAR(255),
   series BOOLEAN,
   synopsis VARCHAR(255),
   price DOUBLE PRECISION,
   promotional_price DOUBLE PRECISION,
   collection VARCHAR(255),
   category VARCHAR(255),
   availability VARCHAR(255),
   format VARCHAR(255),
   stock_available INTEGER NOT NULL,
   weight DOUBLE PRECISION,
   CONSTRAINT pk_book PRIMARY KEY (id)
);

create TABLE catalogservice.author (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   isni VARCHAR(255),
   name VARCHAR(255),
   original_full_name VARCHAR(255),
   date_of_birth VARCHAR(255),
   place_of_birth VARCHAR(255),
   date_of_death VARCHAR(255),
   place_of_death VARCHAR(255),
   about VARCHAR(255),
   CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE catalogservice.book_sample (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   book_id BIGINT,
   sample VARCHAR(1024),
   CONSTRAINT pk_book_sample PRIMARY KEY (id)
);

CREATE TABLE catalogservice.language (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   code VARCHAR(10),
   CONSTRAINT pk_language PRIMARY KEY (id)
);

CREATE TABLE catalogservice.tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   value VARCHAR(50),
   CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE catalogservice.publisher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   email VARCHAR(255),
   phone_number VARCHAR(255),
   CONSTRAINT pk_publisher PRIMARY KEY (id)
);