version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "172.25.141.121:5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: catalogservice, keycloak, notificationservice, orderservice, paymentservice, returnservice, shippingservice, stockservice, userservice
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "catalog" ]
      interval: 30s
      timeout: 60s
      retries: 5

    volumes:
      - ./utils/postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    networks:
      - bookstore-network
  catalog-service:
    image: 'catalog-service:latest'
    build:
      context: ./catalog-service
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    container_name: catalog-service
    ports:
      - "10000:10000"
      - "8081:8081"
      - "8000:8000"  #jobrnr dashboard
    environment:
      - POSTGRES_HOST=catalogservice
      - POSTGRES_USER=postgres
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started
    volumes:
      - ./catalog-service/log:/catalog-service/log
    networks:
      - bookstore-network
  stock-service:
    image: 'stock-service:latest'
    build:
      context: ./stock-service
      dockerfile: ./src/main/docker/Dockerfile.jvm
    restart: always
    container_name: stock-service
    ports:
      - "10001:10001"
      - "8082:8082"
    environment:
      - POSTGRES_HOST=stockservice
      - POSTGRES_USER=postgres
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started
    volumes:
      - ./stock-service/log:/stock-service/log
    networks:
      - bookstore-network
  consul:
    image: hashicorp/consul:latest
    command: agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0 --https-port=8501
    ports:
      - "8500:8500"
      - "8501:8501"
      - "8002:8002"
    networks:
      - bookstore-network
  #running kafka without zookeeper (using KRaft)
  #Kafka Service
  kafka:
    image: 'bitnami/kafka:3.4'
    container_name: kafka

    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    ports:
      - '9092:9092'
      - '9094:9094'
    networks:
      - bookstore-network

volumes:
  kafka_data:
    driver: local
networks:
  bookstore-network: