CREATE TABLE stockservice.stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   book_id INTEGER,
   available_units INTEGER,
   pending_units INTEGER,
   creation_date TIMESTAMP WITHOUT TIME ZONE,
   update_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_stock PRIMARY KEY (id)
);
